/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devopshint;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

	String input1 = "noon";
	App app = new App();
	boolean expected = true;

	@Test
	public void isPlaindromeTest() {
		assertEquals(expected, app.isPalindrome(input1));
	}

	// @Test
	// public void isNotPlaindromeTest() {
	// 	assertEquals(false, app.isPalindrome("abc"));
	// }

	

}
